DROP DATABASE IF EXISTS `students_funding_sys`;
CREATE DATABASE IF NOT EXISTS `students_funding_sys` DEFAULT CHARACTER SET 'UTF8';
USE `students_funding_sys`;


CREATE TABLE IF NOT EXISTS production(
id INT UNSIGNED AUTO_INCREMENT KEY,
description VARCHAR(500) NOT NULL UNIQUE,
category VARCHAR(50) NOT NULL UNIQUE,
url VARCHAR(255) NOT NULL UNIQUE
);
